SELECT * FROM InitialCoinOffering
WHERE InitialCoinOffering.InitialCoinOfferingSourceId = 3
AND InitialCoinOffering.Label NOT LIKE '%health%'
AND InitialCoinOffering.Label NOT LIKE '%real estate%'
AND InitialCoinOffering.Label NOT LIKE '%banking%'
AND InitialCoinOffering.Label NOT LIKE '%certification%'
AND InitialCoinOffering.Label NOT LIKE '%conference%'
AND InitialCoinOffering.Label NOT LIKE '%investment%'
AND InitialCoinOffering.Label NOT LIKE '%supply%'
AND InitialCoinOffering.Label NOT LIKE '%food%'
AND InitialCoinOffering.Label NOT LIKE '%consumer%'
AND InitialCoinOffering.Label NOT LIKE '%staff%'
AND InitialCoinOffering.Label NOT LIKE '%venture%'
AND InitialCoinOffering.Label NOT LIKE '%capital%'
AND InitialCoinOffering.Label NOT LIKE '%associat%'
AND InitialCoinOffering.Label NOT LIKE '%advisor%'
AND InitialCoinOffering.Label NOT LIKE '%community%'
AND InitialCoinOffering.Label NOT LIKE '%meet%'
AND InitialCoinOffering.Label NOT LIKE '%ecosystem%'
AND InitialCoinOffering.Label NOT LIKE '%developer%'
AND InitialCoinOffering.Label NOT LIKE '%education%'
AND InitialCoinOffering.Label NOT LIKE '%university%'
AND InitialCoinOffering.Label NOT LIKE '%india%'
AND InitialCoinOffering.Label NOT LIKE '%china%'
AND InitialCoinOffering.Label NOT LIKE '%loan%'
AND InitialCoinOffering.Label NOT LIKE '%lending%'
AND InitialCoinOffering.Label NOT LIKE '%medical%'
AND InitialCoinOffering.Label NOT LIKE '%partner%'
AND InitialCoinOffering.Label NOT LIKE '%insurance%'
AND InitialCoinOffering.Label NOT LIKE '%travel%'
AND InitialCoinOffering.Label NOT LIKE '%social%'
AND InitialCoinOffering.Label NOT LIKE '%crypto%'
AND InitialCoinOffering.Label NOT LIKE '%book%'
AND InitialCoinOffering.Label NOT LIKE '%entertainment%'
AND InitialCoinOffering.Label NOT LIKE '%science%'
AND InitialCoinOffering.Label NOT LIKE '%token%'
AND InitialCoinOffering.Label NOT LIKE '%ltd.%'
AND InitialCoinOffering.Label NOT LIKE '%music%'
AND InitialCoinOffering.Label NOT LIKE '%gaming%'
AND InitialCoinOffering.Label NOT LIKE '%gambling%'
AND InitialCoinOffering.Label NOT LIKE '%casino%'
AND InitialCoinOffering.Label NOT LIKE '%corporate%'
AND InitialCoinOffering.Label NOT LIKE '%holding%'
AND InitialCoinOffering.Label NOT LIKE '%crowd%'
AND InitialCoinOffering.Label NOT LIKE '%energy%'
AND InitialCoinOffering.Label NOT LIKE '%automation%'
AND InitialCoinOffering.Label NOT LIKE '%automotive%'
AND InitialCoinOffering.Label NOT LIKE '%advertis%'
AND InitialCoinOffering.Label NOT LIKE '%exchange%'
AND InitialCoinOffering.Label NOT LIKE '%consult%'
AND InitialCoinOffering.Label NOT LIKE '%law%'
AND InitialCoinOffering.Label NOT LIKE '%coin%'
AND InitialCoinOffering.Label NOT LIKE '%power%'
AND InitialCoinOffering.Label NOT LIKE '%asia%'
AND InitialCoinOffering.Label NOT LIKE '%trade%'
AND InitialCoinOffering.Label NOT LIKE '%stock%'
AND InitialCoinOffering.Label NOT LIKE '%world%'
AND InitialCoinOffering.Label NOT LIKE '%marketing%'
AND InitialCoinOffering.Label NOT LIKE '%learning%'
AND InitialCoinOffering.Label NOT LIKE '%accounting%'
AND InitialCoinOffering.Label NOT LIKE '%legal%'
AND InitialCoinOffering.Label NOT LIKE '%market%'
AND InitialCoinOffering.Label NOT LIKE '% LLC%'
AND InitialCoinOffering.Label NOT LIKE '%inc.%'
AND InitialCoinOffering.Label NOT LIKE '% think %'
AND InitialCoinOffering.Label NOT LIKE '% online %'
AND InitialCoinOffering.Label NOT LIKE '%hospitality%'
AND InitialCoinOffering.Label NOT LIKE '% gmbh %'
AND InitialCoinOffering.Label NOT LIKE '%lottery%'
AND InitialCoinOffering.Label NOT LIKE '%launcher%'
AND InitialCoinOffering.Label NOT LIKE '% center %'
AND InitialCoinOffering.Label NOT LIKE '% future %'
AND InitialCoinOffering.Label NOT LIKE '% wealth %'
AND InitialCoinOffering.Label NOT LIKE '% group %'
AND InitialCoinOffering.Label NOT LIKE '%currency%'
AND InitialCoinOffering.Label NOT LIKE '%agency%'
AND InitialCoinOffering.Label NOT LIKE '%fashion%'
AND InitialCoinOffering.Label NOT LIKE '% public %'
AND InitialCoinOffering.Label NOT LIKE '% knowledge %'
AND InitialCoinOffering.Label NOT LIKE '%event%'
AND InitialCoinOffering.Label NOT LIKE '%global%'
AND InitialCoinOffering.Label NOT LIKE '%solution%'
AND InitialCoinOffering.Label NOT LIKE '%training%'
AND InitialCoinOffering.Label NOT LIKE '%mining%'
AND InitialCoinOffering.Label NOT LIKE '%council%'
AND InitialCoinOffering.Label NOT LIKE '%board%'
AND InitialCoinOffering.Label NOT LIKE '%universal%'